@SummerProj_HostAddress = http://localhost:5049

### Отримати всі угоди
GET {{SummerProj_HostAddress}}/api/Agreement
Accept: application/json

### Отримати угоду за ID
GET {{SummerProj_HostAddress}}/api/Agreement/{{agreementId}}
Accept: application/json

### Створити нову угоду
POST {{SummerProj_HostAddress}}/api/Agreement
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "workerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "companieId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "position": "Software Developer",
  "commission": 10
}

### Оновити угоду
PUT {{SummerProj_HostAddress}}/api/Agreement/{{agreementId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "workerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "companieId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "position": "Senior Software Developer",
  "commission": 15
}

### Видалити угоду
DELETE {{SummerProj_HostAddress}}/api/Agreement/{{agreementId}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Приклад створення угоди з реальними даними
POST {{SummerProj_HostAddress}}/api/Agreement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjNkMTI1ZWEwLTdmOTAtNGI4Yy05ZWJiLTJiNDRlMmZmY2NjMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ6eGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ6eGMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc1MTg1NDU1MiwiaXNzIjoiWW91cklzc3VlciIsImF1ZCI6IllvdXJBdWRpZW5jZSJ9.KWVFpmo1DW-AtIe10Hra8HaVc9lj7irFoV5FY2Y8P9I

{
  "workerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "companieId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "position": "Full Stack Developer",
  "commission": 12.5
} 